### PR TITLE
Stabilize batch classes.

### PR DESCRIPTION
**Pull request by RageZBla**
Hey there, this PR fixes the return values of MongoInsertBatch/MongoUpdateBatch/MongoDeleteBatch.

### CODE REVIEW

**Comment by RageZBla** [comment]
This PR does not fixes the issue with MongoUpdateBatch returning the list of upserted documents index. 

I was not sure what you wanted to for this. In my opinion we have better just to change the test case to use `assertArraySubset`

**Comment by alcaeus** [comment]
Did you mean to open this against the branch for #28?

**Comment by RageZBla** [comment]
Yes actually I was a bit too quick clicking on the create button. Do you
want me to close this and reopen a different pull request?

**Comment by alcaeus** [comment]
It's ok, I'll merge this manually later today. Thanks!

**Comment by alcaeus** [comment]
Merged into #28.

**Pull request closed without merging**
