### PR TITLE
add unit test of hasNext()

### PR DESCRIPTION
**Pull request by shanghaiyangming**

### CODE REVIEW

**Comment by alcaeus** [comment]
Can you please rebase the branch?

**Comment by shanghaiyangming** [comment]
please close this pull i will pull another request~

**Comment by alcaeus** [comment]
Feel free to re-use this pull request or close it yourself - I'll leave that up to you.

**Comment by alcaeus** [comment]
Closing for lack of input - while the test works with `ext-mongo` the `hasNext` method is a bit more complex than just returning `$this->valid()`.

**Pull request closed without merging**
