### PR TITLE
Allow create Mongo instances

### PR DESCRIPTION
**Pull request by Maks3w**
Make it compatible with Doctrine ODM

### CODE REVIEW

**Comment by alcaeus** [comment]
Let me stop you right there ;)
doctrine/mongodb does not work with this adapter right now because of a version check for ext-mongo > 1.3 (a userland library can't hook into a call to `extension_loaded` for example). The upcoming 1.3 release of doctrine/mongodb will remove support for older driver versions and thus remove the hardcoded version checks, including the attempt to create an instance of `\Mongo`: https://github.com/doctrine/mongodb/pull/238/files#diff-a8cbdf168edf86f60dbf5bea26d66a14L283

I'm closing this for now since there's no point implementing an API people should've stopped using years ago.

**Comment by Maks3w** [comment]
@alcaeus Please post in some part what are the current workarounds for PHP 7. It's complicated to follow the doctrine progress with locked conversations etc.

Please update https://github.com/doctrine/mongodb/issues/239 adding a comment with a link to this repo and the need of use doctrine/mongodb master branch

**Comment by alcaeus** [comment]
I will once there is an official way to run ODM on PHP 7. To put this into perspective: last time I tried to run the ODM test suite with the adapter installed it failed hard and didn't even finish. For now, the timeline is:
1. Finish up with #28. This will ensure consistency to `ext-mongo`, even if not everything is implemented yet
2. Tag a 0.1.0 release - this will tell people that while the library is still under development, you can start using it **if you know what you're doing**
3. Start stabilizing issues and get this adapter to play nice enough to work for Doctrine ODM - this might be a complicated issue though
4. Tag a stable 1.0.0 release.

Once we've arrived at step 4, there will be enough information for everyone to use this without having to know about what it does and what it doesn't. Until then, if you want to use it, expect to run into hard issues, failures, data loss or even worse issues. Right now, if you want to use it, that's your own choice, but I'm not gonna tell ODM people to "just install this adapter and upgrade to PHP 7 already". Installing a `dev-master` version of a database driver adapter that doesn't even have a stable release yet is not something you should do lightly. If you can't get past that initial hurdle of installing it you're going to have a bad time when the first issue arises. So, once more for good measure: **THIS LIBRARY IS NOT YET SUITED FOR PRODUCTION USE**.

That said - you're welcome to try the library and create issues for errors, failures, problems, anything else you might find. The installation instructions in this readme should work for people - unfortunately composer doesn't make it all that easy creating polyfills for extensions that just work by adding them to the `require` section in composer.json. I appreciate a bug report if you have something that doesn't work. Somewhere in that timeline above there's a "tag new versions for doctrine/mongodb and ODM", but there are other factors at play there. Upcoming releases will work this this adapter, the current stable releases don't.

**Comment by Maks3w** [comment]
I'm starting with ODM and up to now I'm able of persist instances.

# composer.json

```js
    "require": {
        "alcaeus/mongo-php-adapter": "dev-master",
        "doctrine/mongodb": "dev-master",
        "doctrine/mongodb-odm": "^1.0",
        "php": "^7.0"
    },
    "provide": {
        "ext-mongo": "1.6.12"
    }
```

# Dockerfile
```
FROM php:7.0-fpm

RUN buildDeps="libssl-dev" \
    && set -x \
    && apt-get update && apt-get install -y $buildDeps --no-install-recommends && rm -rf /var/lib/apt/lists/* \
    && pecl install mongodb \
    && docker-php-ext-enable mongodb \
    && rm -rf /tmp/pear \
    && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false -o APT::AutoRemove::SuggestsImportant=false $buildDeps
```

**Comment by Maks3w** [comment]
If you could paste these instructions on doctrine/mongodb#239 more people will be able to test in their "bleeding edge" projects

**Pull request closed without merging**
