### PR TITLE
throw MongoWriteConcern Exception when it happens

### PR DESCRIPTION
**Pull request by prolic**

### CODE REVIEW

**Comment by alcaeus** [comment]
Can you please add tests for this?

**Comment by prolic** [comment]
@alcaeus test updated

**Comment by prolic** [comment]
Btw: on my local machine 2 tests are failing, but seem to be green on travis:

```
1) Alcaeus\MongoDbAdapter\Tests\Mongo\MongoCollectionTest::testDeleteIndexUsingIndexName
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     'nIndexesWas' => 2
     'errmsg' => 'index not found with name [bar_1]'
     'ok' => 0.0
-    'code' => 27
 )

/home/sasa/code/mongo-php-adapter/tests/Alcaeus/MongoDbAdapter/Mongo/MongoCollectionTest.php:1118

2) Alcaeus\MongoDbAdapter\Tests\Mongo\MongoCollectionTest::testDeleteIndexesForNonExistingCollection
Failed asserting that Array &0 (
    'ok' => 0.0
    'errmsg' => 'ns not found'
) is identical to Array &0 (
    'ok' => 0.0
    'errmsg' => 'ns not found'
    'code' => 26
).
```

**Comment by alcaeus** [comment]
Which MongoDB version are you running locally?

**Comment by prolic** [comment]
mongod --version                                                                                  :(
db version v3.0.5
git version: 8bc4ae20708dbb493cb09338d9e7be6698e4a3a3

**Comment by prolic** [comment]
And the tests failing locally is also in current master, so unrelated to this PR.

**Comment by alcaeus** [comment]
Thanks for the info. I'll take a look at the test failures - could be related to some changes in MongoDB.

**Comment by prolic** [comment]
@alcaeus is it ready for merge? sorry, but i am currently waiting to get this in and released :-)

**Comment by alcaeus** [comment]
I apologise for the lack of feedback here, the past few days have been...different. While applying the patch to the 1.0 branch I noticed that there were a couple of other issues so I'm just taking the time to make sure everything works as expected.

**Comment by alcaeus** [comment]
I've created #120 which builds on top of your changes. Since the MongoWriteConcernException also returns a result document which contains information about the failing writes and how much has succeeded, I decided to not include this in the ExceptionConverter. I'll make sure update and delete bulk operations work properly tomorrow.

**Comment by prolic** [comment]
Thank you!

**Comment by alcaeus** [comment]
Superseded by #120, closing.

**Pull request closed without merging**
