### PR TITLE
Run testsuite against ext-mongo

### PR DESCRIPTION
**Pull request by alcaeus**
This PR adds ext-mongo to the build matrix in an effort to ensure the library behaves the same as ext-mongo does. This is achieved by running the tests with ext-mongo installed.

This PR will be used to stabilize the library before moving to a stable release.

### CODE REVIEW

**Comment by alcaeus** [comment]
@bashofmann Can you take a look at the MongoCursor class? I had to make some changes to `valid()` and `key()` to replicate the behavior of the ext-mongo class.

**Comment by alcaeus** [comment]
Note: the aggregate method is failing due to mongodb/mongo-php-library#107.

**Comment by bashofmann** [comment]
@alcaeus Looks good, our test suite runs successfully through with this branch

**Comment by alcaeus** [comment]
@bashofmann Great, thanks!

**Pull request merged**
